language: python
python:
  - "3.5"
  - "3.6"
install: "pip3 install -r requirements.txt"
script:
  - "python3 setup.py test"
  - "update_wiki.sh"
#  - if [ "$TRAVIS_BRANCH" = "master" ]; then update_wiki.sh; fi